<a href="https://colab.research.google.com/github/shilphypg/MAHE_MSc.DS/blob/master/Python_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('/content/cereal.csv')
df

FileNotFoundError: [Errno 2] No such file or directory: '/content/cereal.csv'

In [4]:
df1=pd.read_csv('/content/SSLC_Scores.csv')
df1

,Sl,Student,Gender,Age,Hobbies,Kan,Eng,Hin,Math,Sci,S.S.,Total,Perc,Result
0,1,Adhil Pasha,m,17.0,cricket,81,66,77,52,45,59,380,76.0,pass
1,2,Anjali P.S,f,16.0,chess,49,35,25,25,25,33,192,38.0,fail
2,3,Asfiya Z,f,17.0,cricket,60,53,66,47,48,66,340,68.0,pass
3,4,Bharath Kumar M.V,m,NaN,checkers,85,62,68,46,64,78,403,81.0,pass
4,5,Bhargav Reddy Y.S,m,NaN,hockey,90,42,64,40,58,72,366,73.0,pass
5,6,Bhavani P.V,f,15.0,chess,84,47,57,34,45,53,320,64.0,pass
6,7,Chandra Kanth V.N,m,16.0,chess,77,59,61,38,46,59,340,68.0,pass
7,8,Dharani R.B,f,16.0,checkers,78,56,51,53,52,57,347,69.0,pass
8,9,Divya T.D,f,17.0,checkers,80,51,70,33,54,33,321,64.0,pass
9,10,Janaki G.J,f,NaN,checkers,94,55,64,41,54,48,356,71.0,pass
10,11,Ghansi Rani S,f,17.0,checkers,92,62,71,50,52,59,386,77.0,pass
11,12,Keerthi M.N,m,NaN,chess,74,30,37,30,40,45,256,51.0,pass
12,13,Misbha Sulthana,f,12.0,chess,66,53,73,34,40,41,307,61.0,pass
13,14,Mohammed Sulaiman,m,17.0,cricket,72,66,72,41,58,50,359,72.0,pass
14,15,Naresha K.A,m,NaN,cricket,60,38,44,30,46,46,264,53.0,pass
15,16,Neha Khanam,f,15.0,cricket,51,51,56,44,44,40,286,57.0,pass
16,17,Noorain Sadiya,f,16.0,cricket,60,57,72,34,43,54,320,64.0,pass
17,18,Sameer Khan,m,18.0,cricket,92,71,79,53,71,75,441,88.0,pass
18,19,Samreen,m,16.0,cricket,90,53,76,45,50,47,361,72.0,pass
19,20,Sanjay Reddy P.G,m,16.0,cricket,83,44,57,28,43,59,314,63.0,pass
20,21,Shanmukha G.S,m,18.0,chess,72,34,37,17,38,23,221,46.0,pass
21,22,Shravani C.N,f,16.0,chess,82,54,52,30,52,57,327,65.0,pass
22,23,Sindhu B.C,f,16.0,chess,91,65,78,47,67,73,421,84.0,pass
23,24,Sofiya Khanam,f,17.0,checkers,67,55,66,38,54,46,326,65.0,pass
24,25,Srikanth K.B,f,16.0,volleyball,78,35,Ab,Ab,49,59,221,44.0,fail
25,26,Sushmitha P,f,16.0,volleyball,77,42,40,43,51,50,303,61.0,pass
26,27,Syed Safeer,m,17.0,cricket,82,61,74,42,61,70,390,78.0,pass
27,28,Tanziya Banu A.I,f,16.0,checkers,93,69,79,50,71,76,438,87.6,pass
28,29,Upendra C.V,m,17.0,cricket,70,40,35,18,36,44,243,51.0,pass
29,30,Veena Reddy R,f,16.0,checkers,85,49,40,50,53,64,341,68.0,pass
30,31,Vijay Kumar T.N,f,16.0,cricket,85,61,67,42,61,68,384,77.0,pass
31,12,Keerthi M.N,m,NaN,chess,74,30,37,30,40,45,256,51.0,pass
32,24,Sofiya Khanam,f,17.0,checkers,67,55,66,38,54,46,326,65.0,pass
33,25,Srikanth K.B,f,16.0,volleyball,78,35,Ab,Ab,49,59,221,44.0,fail
34,26,Sushmitha P,f,16.0,volleyball,77,42,40,43,51,50,303,61.0,pass
35,21,Shanmukha G.S,m,18.0,chess,72,34,37,17,38,23,221,46.0,pass
36,22,Shravani C.N,f,16.0,chess,82,54,52,30,52,57,327,65.0,pass

In [5]:
#understand the dataframe, shape gives size of the dataset
df1.shape

(37, 14)

In [8]:
df1.columns # to list the available columns

Index(['Sl', 'Student', 'Gender ', 'Age', 'Hobbies ', 'Kan', 'Eng', 'Hin',
       'Math', 'Sci', 'S.S.', 'Total', 'Perc', 'Result '],
      dtype='object')

In [6]:
len(df1)#to show row

37

In [7]:
df1.describe()#understand the dataframe, any outliers,any missing values

,Sl,Age,Kan,Eng,Sci,S.S.,Total,Perc
count,37.000000,31.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000
mean,16.918919,16.290323,77.027027,50.432432,50.135135,53.621622,322.378378,64.556757
std,8.772996,1.101319,11.424843,11.586727,9.801253,13.754497,63.669438,12.530508
min,1.000000,12.000000,49.000000,30.000000,25.000000,23.000000,192.000000,38.000000
25%,10.000000,16.000000,72.000000,42.000000,44.000000,46.000000,286.000000,57.000000
50%,18.000000,16.000000,78.000000,53.000000,51.000000,54.000000,326.000000,65.000000
75%,24.000000,17.000000,85.000000,59.000000,54.000000,59.000000,361.000000,72.000000
max,31.000000,18.000000,94.000000,71.000000,71.000000,78.000000,441.000000,88.000000

In [9]:
df1[["Student"]].describe()

            Student
count            37
unique           31
top     Sushmitha P
freq              2

In [10]:
df1.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Columns: 14 entries, Sl to Result
dtypes: float64(2), int64(6), object(6)
memory usage: 4.2+ KB

In [12]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Sl        37 non-null     int64
 1   Student   37 non-null     object
 2   Gender    37 non-null     object
 3   Age       31 non-null     float64
 4   Hobbies   37 non-null     object
 5   Kan       37 non-null     int64
 6   Eng       37 non-null     int64
 7   Hin       37 non-null     object
 8   Math      37 non-null     object
 9   Sci       37 non-null     int64
 10  S.S.      37 non-null     int64
 11  Total     37 non-null     int64
 12  Perc      37 non-null     float64
 13  Result    37 non-null     object
dtypes: float64(2), int64(6), object(6)
memory usage: 4.2+ KB

In [13]:
df1.dtypes

Sl            int64
Student      object
Gender       object
Age         float64
Hobbies      object
Kan           int64
Eng           int64
Hin          object
Math         object
Sci           int64
S.S.          int64
Total         int64
Perc        float64
Result       object
dtype: object

In [14]:
df1.tail()

,Sl,Student,Gender,Age,Hobbies,Kan,Eng,Hin,Math,Sci,S.S.,Total,Perc,Result
32,24,Sofiya Khanam,f,17.0,checkers,67,55,66,38,54,46,326,65.0,pass
33,25,Srikanth K.B,f,16.0,volleyball,78,35,Ab,Ab,49,59,221,44.0,fail
34,26,Sushmitha P,f,16.0,volleyball,77,42,40,43,51,50,303,61.0,pass
35,21,Shanmukha G.S,m,18.0,chess,72,34,37,17,38,23,221,46.0,pass
36,22,Shravani C.N,f,16.0,chess,82,54,52,30,52,57,327,65.0,pass

In [17]:
df1.sample() #to check random values

,Sl,Student,Gender,Age,Hobbies,Kan,Eng,Hin,Math,Sci,S.S.,Total,Perc,Result
0,1,Adhil Pasha,m,17.0,cricket,81,66,77,52,45,59,380,76.0,pass

In [18]:
df1.sample(10)

,Sl,Student,Gender,Age,Hobbies,Kan,Eng,Hin,Math,Sci,S.S.,Total,Perc,Result
8,9,Divya T.D,f,17.0,checkers,80,51,70,33,54,33,321,64.0,pass
12,13,Misbha Sulthana,f,12.0,chess,66,53,73,34,40,41,307,61.0,pass
11,12,Keerthi M.N,m,NaN,chess,74,30,37,30,40,45,256,51.0,pass
3,4,Bharath Kumar M.V,m,NaN,checkers,85,62,68,46,64,78,403,81.0,pass
10,11,Ghansi Rani S,f,17.0,checkers,92,62,71,50,52,59,386,77.0,pass
31,12,Keerthi M.N,m,NaN,chess,74,30,37,30,40,45,256,51.0,pass
9,10,Janaki G.J,f,NaN,checkers,94,55,64,41,54,48,356,71.0,pass
25,26,Sushmitha P,f,16.0,volleyball,77,42,40,43,51,50,303,61.0,pass
28,29,Upendra C.V,m,17.0,cricket,70,40,35,18,36,44,243,51.0,pass
35,21,Shanmukha G.S,m,18.0,chess,72,34,37,17,38,23,221,46.0,pass

In [19]:
df1.columns

Index(['Sl', 'Student', 'Gender ', 'Age', 'Hobbies ', 'Kan', 'Eng', 'Hin',
       'Math', 'Sci', 'S.S.', 'Total', 'Perc', 'Result '],
      dtype='object')

In [23]:
import pandas as pd
df1=pd.read_csv('/content/SSLC_Scores.csv')
df1

,Sl,Student,Gender,Age,Hobbies,Kan,Eng,Hin,Math,Sci,S.S.,Total,Perc,Result
0,1,Adhil Pasha,m,17.0,cricket,81,66,77,52,45,59,380,76.0,pass
1,2,Anjali P.S,f,16.0,chess,49,35,25,25,25,33,192,38.0,fail
2,3,Asfiya Z,f,17.0,cricket,60,53,66,47,48,66,340,68.0,pass
3,4,Bharath Kumar M.V,m,NaN,checkers,85,62,68,46,64,78,403,81.0,pass
4,5,Bhargav Reddy Y.S,m,NaN,hockey,90,42,64,40,58,72,366,73.0,pass
5,6,Bhavani P.V,f,15.0,chess,84,47,57,34,45,53,320,64.0,pass
6,7,Chandra Kanth V.N,m,16.0,chess,77,59,61,38,46,59,340,68.0,pass
7,8,Dharani R.B,f,16.0,checkers,78,56,51,53,52,57,347,69.0,pass
8,9,Divya T.D,f,17.0,checkers,80,51,70,33,54,33,321,64.0,pass
9,10,Janaki G.J,f,NaN,checkers,94,55,64,41,54,48,356,71.0,pass
10,11,Ghansi Rani S,f,17.0,checkers,92,62,71,50,52,59,386,77.0,pass
11,12,Keerthi M.N,m,NaN,chess,74,30,37,30,40,45,256,51.0,pass
12,13,Misbha Sulthana,f,12.0,chess,66,53,73,34,40,41,307,61.0,pass
13,14,Mohammed Sulaiman,m,17.0,cricket,72,66,72,41,58,50,359,72.0,pass
14,15,Naresha K.A,m,NaN,cricket,60,38,44,30,46,46,264,53.0,pass
15,16,Neha Khanam,f,15.0,cricket,51,51,56,44,44,40,286,57.0,pass
16,17,Noorain Sadiya,f,16.0,cricket,60,57,72,34,43,54,320,64.0,pass
17,18,Sameer Khan,m,18.0,cricket,92,71,79,53,71,75,441,88.0,pass
18,19,Samreen,m,16.0,cricket,90,53,76,45,50,47,361,72.0,pass
19,20,Sanjay Reddy P.G,m,16.0,cricket,83,44,57,28,43,59,314,63.0,pass
20,21,Shanmukha G.S,m,18.0,chess,72,34,37,17,38,23,221,46.0,pass
21,22,Shravani C.N,f,16.0,chess,82,54,52,30,52,57,327,65.0,pass
22,23,Sindhu B.C,f,16.0,chess,91,65,78,47,67,73,421,84.0,pass
23,24,Sofiya Khanam,f,17.0,checkers,67,55,66,38,54,46,326,65.0,pass
24,25,Srikanth K.B,f,16.0,volleyball,78,35,Ab,Ab,49,59,221,44.0,fail
25,26,Sushmitha P,f,16.0,volleyball,77,42,40,43,51,50,303,61.0,pass
26,27,Syed Safeer,m,17.0,cricket,82,61,74,42,61,70,390,78.0,pass
27,28,Tanziya Banu A.I,f,16.0,checkers,93,69,79,50,71,76,438,87.6,pass
28,29,Upendra C.V,m,17.0,cricket,70,40,35,18,36,44,243,51.0,pass
29,30,Veena Reddy R,f,16.0,checkers,85,49,40,50,53,64,341,68.0,pass
30,31,Vijay Kumar T.N,f,16.0,cricket,85,61,67,42,61,68,384,77.0,pass
31,12,Keerthi M.N,m,NaN,chess,74,30,37,30,40,45,256,51.0,pass
32,24,Sofiya Khanam,f,17.0,checkers,67,55,66,38,54,46,326,65.0,pass
33,25,Srikanth K.B,f,16.0,volleyball,78,35,Ab,Ab,49,59,221,44.0,fail
34,26,Sushmitha P,f,16.0,volleyball,77,42,40,43,51,50,303,61.0,pass
35,21,Shanmukha G.S,m,18.0,chess,72,34,37,17,38,23,221,46.0,pass
36,22,Shravani C.N,f,16.0,chess,82,54,52,30,52,57,327,65.0,pass

In [24]:
df1['Hin']=df1['Hin'].astype('int')
df1

ValueError: invalid literal for int() with base 10: 'Ab'

In [26]:
df1.isna().sum()

Sl          0
Student     0
Gender      0
Age         6
Hobbies     0
Kan         0
Eng         0
Hin         0
Math        0
Sci         0
S.S.        0
Total       0
Perc        0
Result      0
dtype: int64

In [27]:
# Check which rows have non-numeric values
non_numeric_rows = df1[~df1['Hin'].str.isnumeric()]
print(non_numeric_rows)

# Filter out non-numeric values and convert the rest
df1['Hin'] = pd.to_numeric(df1['Hin'], errors='coerce').fillna(0).astype('int')

print(df1)

    Sl       Student Gender    Age    Hobbies   Kan  Eng Hin Math  Sci  S.S.  \
24  25  Srikanth K.B       f  16.0  volleyball   78   35  Ab   Ab   49    59
33  25  Srikanth K.B       f  16.0  volleyball   78   35  Ab   Ab   49    59

    Total  Perc Result
24    221  44.0    fail
33    221  44.0    fail
    Sl            Student Gender    Age    Hobbies   Kan  Eng  Hin Math  Sci  \
0    1        Adhil Pasha       m  17.0     cricket   81   66   77   52   45
1    2         Anjali P.S       f  16.0       chess   49   35   25   25   25
2    3           Asfiya Z       f  17.0     cricket   60   53   66   47   48
3    4  Bharath Kumar M.V       m   NaN    checkers   85   62   68   46   64
4    5  Bhargav Reddy Y.S       m   NaN     hockey    90   42   64   40   58
5    6        Bhavani P.V       f  15.0       chess   84   47   57   34   45
6    7  Chandra Kanth V.N       m  16.0       chess   77   59   61   38   46
7    8        Dharani R.B       f  16.0    checkers   78   56   51   53   52
8    9          Divya T.D       f  17.0    checkers   80   51   70   33   54
9   10         Janaki G.J       f   NaN    checkers   94   55   64   41   54
10  11      Ghansi Rani S       f  17.0    checkers   92   62   71   50   52
11  12        Keerthi M.N       m   NaN       chess   74   30   37   30   40
12  13    Misbha Sulthana       f  12.0       chess   66   53   73   34   40
13  14  Mohammed Sulaiman       m  17.0     cricket   72   66   72   41   58
14  15        Naresha K.A       m   NaN     cricket   60   38   44   30   46
15  16        Neha Khanam       f  15.0     cricket   51   51   56   44   44
16  17     Noorain Sadiya       f  16.0     cricket   60   57   72   34   43
17  18        Sameer Khan       m  18.0     cricket   92   71   79   53   71
18  19            Samreen       m  16.0     cricket   90   53   76   45   50
19  20   Sanjay Reddy P.G       m  16.0     cricket   83   44   57   28   43
20  21      Shanmukha G.S       m  18.0       chess   72   34   37   17   38
21  22       Shravani C.N       f  16.0       chess   82   54   52   30   52
22  23         Sindhu B.C       f  16.0       chess   91   65   78   47   67
23  24      Sofiya Khanam       f  17.0    checkers   67   55   66   38   54
24  25       Srikanth K.B       f  16.0  volleyball   78   35    0   Ab   49
25  26        Sushmitha P       f  16.0  volleyball   77   42   40   43   51
26  27        Syed Safeer       m  17.0     cricket   82   61   74   42   61
27  28   Tanziya Banu A.I       f  16.0    checkers   93   69   79   50   71
28  29        Upendra C.V       m  17.0     cricket   70   40   35   18   36
29  30      Veena Reddy R       f  16.0    checkers   85   49   40   50   53
30  31    Vijay Kumar T.N       f  16.0     cricket   85   61   67   42   61
31  12        Keerthi M.N       m   NaN       chess   74   30   37   30   40
32  24      Sofiya Khanam       f  17.0    checkers   67   55   66   38   54
33  25       Srikanth K.B       f  16.0  volleyball   78   35    0   Ab   49
34  26        Sushmitha P       f  16.0  volleyball   77   42   40   43   51
35  21      Shanmukha G.S       m  18.0       chess   72   34   37   17   38
36  22       Shravani C.N       f  16.0       chess   82   54   52   30   52

    S.S.  Total  Perc Result
0     59    380  76.0    pass
1     33    192  38.0    fail
2     66    340  68.0    pass
3     78    403  81.0    pass
4     72    366  73.0    pass
5     53    320  64.0    pass
6     59    340  68.0    pass
7     57    347  69.0    pass
8     33    321  64.0    pass
9     48    356  71.0    pass
10    59    386  77.0    pass
11    45    256  51.0    pass
12    41    307  61.0    pass
13    50    359  72.0    pass
14    46    264  53.0    pass
15    40    286  57.0    pass
16    54    320  64.0    pass
17    75    441  88.0    pass
18    47    361  72.0    pass
19    59    314  63.0    pass
20    23    221  46.0    pass
21    57    327  65.0    pass
22    73    421  84.0    pass
23    46    326  65.0    pass
24    59    221  44.0    fail
25    50    303  61.0    pass
26    70    390  78.0    pass
27    76    438  87.6    pass
28    44    243  51.0    pass
29    64    341  68.0    pass
30    68    384  77.0    pass
31    45    256  51.0    pass
32    46    326  65.0    pass
33    59    221  44.0    fail
34    50    303  61.0    pass
35    23    221  46.0    pass
36    57    327  65.0    pass

In [28]:
# Replace non-numeric values with a specific value, e.g., 0
df1['Hin'] = pd.to_numeric(df1['Hin'], errors='coerce').fillna(0).astype('int')

print(df1)

    Sl            Student Gender    Age    Hobbies   Kan  Eng  Hin Math  Sci  \
0    1        Adhil Pasha       m  17.0     cricket   81   66   77   52   45
1    2         Anjali P.S       f  16.0       chess   49   35   25   25   25
2    3           Asfiya Z       f  17.0     cricket   60   53   66   47   48
3    4  Bharath Kumar M.V       m   NaN    checkers   85   62   68   46   64
4    5  Bhargav Reddy Y.S       m   NaN     hockey    90   42   64   40   58
5    6        Bhavani P.V       f  15.0       chess   84   47   57   34   45
6    7  Chandra Kanth V.N       m  16.0       chess   77   59   61   38   46
7    8        Dharani R.B       f  16.0    checkers   78   56   51   53   52
8    9          Divya T.D       f  17.0    checkers   80   51   70   33   54
9   10         Janaki G.J       f   NaN    checkers   94   55   64   41   54
10  11      Ghansi Rani S       f  17.0    checkers   92   62   71   50   52
11  12        Keerthi M.N       m   NaN       chess   74   30   37   30   40
12  13    Misbha Sulthana       f  12.0       chess   66   53   73   34   40
13  14  Mohammed Sulaiman       m  17.0     cricket   72   66   72   41   58
14  15        Naresha K.A       m   NaN     cricket   60   38   44   30   46
15  16        Neha Khanam       f  15.0     cricket   51   51   56   44   44
16  17     Noorain Sadiya       f  16.0     cricket   60   57   72   34   43
17  18        Sameer Khan       m  18.0     cricket   92   71   79   53   71
18  19            Samreen       m  16.0     cricket   90   53   76   45   50
19  20   Sanjay Reddy P.G       m  16.0     cricket   83   44   57   28   43
20  21      Shanmukha G.S       m  18.0       chess   72   34   37   17   38
21  22       Shravani C.N       f  16.0       chess   82   54   52   30   52
22  23         Sindhu B.C       f  16.0       chess   91   65   78   47   67
23  24      Sofiya Khanam       f  17.0    checkers   67   55   66   38   54
24  25       Srikanth K.B       f  16.0  volleyball   78   35    0   Ab   49
25  26        Sushmitha P       f  16.0  volleyball   77   42   40   43   51
26  27        Syed Safeer       m  17.0     cricket   82   61   74   42   61
27  28   Tanziya Banu A.I       f  16.0    checkers   93   69   79   50   71
28  29        Upendra C.V       m  17.0     cricket   70   40   35   18   36
29  30      Veena Reddy R       f  16.0    checkers   85   49   40   50   53
30  31    Vijay Kumar T.N       f  16.0     cricket   85   61   67   42   61
31  12        Keerthi M.N       m   NaN       chess   74   30   37   30   40
32  24      Sofiya Khanam       f  17.0    checkers   67   55   66   38   54
33  25       Srikanth K.B       f  16.0  volleyball   78   35    0   Ab   49
34  26        Sushmitha P       f  16.0  volleyball   77   42   40   43   51
35  21      Shanmukha G.S       m  18.0       chess   72   34   37   17   38
36  22       Shravani C.N       f  16.0       chess   82   54   52   30   52

    S.S.  Total  Perc Result
0     59    380  76.0    pass
1     33    192  38.0    fail
2     66    340  68.0    pass
3     78    403  81.0    pass
4     72    366  73.0    pass
5     53    320  64.0    pass
6     59    340  68.0    pass
7     57    347  69.0    pass
8     33    321  64.0    pass
9     48    356  71.0    pass
10    59    386  77.0    pass
11    45    256  51.0    pass
12    41    307  61.0    pass
13    50    359  72.0    pass
14    46    264  53.0    pass
15    40    286  57.0    pass
16    54    320  64.0    pass
17    75    441  88.0    pass
18    47    361  72.0    pass
19    59    314  63.0    pass
20    23    221  46.0    pass
21    57    327  65.0    pass
22    73    421  84.0    pass
23    46    326  65.0    pass
24    59    221  44.0    fail
25    50    303  61.0    pass
26    70    390  78.0    pass
27    76    438  87.6    pass
28    44    243  51.0    pass
29    64    341  68.0    pass
30    68    384  77.0    pass
31    45    256  51.0    pass
32    46    326  65.0    pass
33    59    221  44.0    fail
34    50    303  61.0    pass
35    23    221  46.0    pass
36    57    327  65.0    pass

In [29]:
df1['Hin']=df1['Hin'].astype('int')
df1

,Sl,Student,Gender,Age,Hobbies,Kan,Eng,Hin,Math,Sci,S.S.,Total,Perc,Result
0,1,Adhil Pasha,m,17.0,cricket,81,66,77,52,45,59,380,76.0,pass
1,2,Anjali P.S,f,16.0,chess,49,35,25,25,25,33,192,38.0,fail
2,3,Asfiya Z,f,17.0,cricket,60,53,66,47,48,66,340,68.0,pass
3,4,Bharath Kumar M.V,m,NaN,checkers,85,62,68,46,64,78,403,81.0,pass
4,5,Bhargav Reddy Y.S,m,NaN,hockey,90,42,64,40,58,72,366,73.0,pass
5,6,Bhavani P.V,f,15.0,chess,84,47,57,34,45,53,320,64.0,pass
6,7,Chandra Kanth V.N,m,16.0,chess,77,59,61,38,46,59,340,68.0,pass
7,8,Dharani R.B,f,16.0,checkers,78,56,51,53,52,57,347,69.0,pass
8,9,Divya T.D,f,17.0,checkers,80,51,70,33,54,33,321,64.0,pass
9,10,Janaki G.J,f,NaN,checkers,94,55,64,41,54,48,356,71.0,pass
10,11,Ghansi Rani S,f,17.0,checkers,92,62,71,50,52,59,386,77.0,pass
11,12,Keerthi M.N,m,NaN,chess,74,30,37,30,40,45,256,51.0,pass
12,13,Misbha Sulthana,f,12.0,chess,66,53,73,34,40,41,307,61.0,pass
13,14,Mohammed Sulaiman,m,17.0,cricket,72,66,72,41,58,50,359,72.0,pass
14,15,Naresha K.A,m,NaN,cricket,60,38,44,30,46,46,264,53.0,pass
15,16,Neha Khanam,f,15.0,cricket,51,51,56,44,44,40,286,57.0,pass
16,17,Noorain Sadiya,f,16.0,cricket,60,57,72,34,43,54,320,64.0,pass
17,18,Sameer Khan,m,18.0,cricket,92,71,79,53,71,75,441,88.0,pass
18,19,Samreen,m,16.0,cricket,90,53,76,45,50,47,361,72.0,pass
19,20,Sanjay Reddy P.G,m,16.0,cricket,83,44,57,28,43,59,314,63.0,pass
20,21,Shanmukha G.S,m,18.0,chess,72,34,37,17,38,23,221,46.0,pass
21,22,Shravani C.N,f,16.0,chess,82,54,52,30,52,57,327,65.0,pass
22,23,Sindhu B.C,f,16.0,chess,91,65,78,47,67,73,421,84.0,pass
23,24,Sofiya Khanam,f,17.0,checkers,67,55,66,38,54,46,326,65.0,pass
24,25,Srikanth K.B,f,16.0,volleyball,78,35,0,Ab,49,59,221,44.0,fail
25,26,Sushmitha P,f,16.0,volleyball,77,42,40,43,51,50,303,61.0,pass
26,27,Syed Safeer,m,17.0,cricket,82,61,74,42,61,70,390,78.0,pass
27,28,Tanziya Banu A.I,f,16.0,checkers,93,69,79,50,71,76,438,87.6,pass
28,29,Upendra C.V,m,17.0,cricket,70,40,35,18,36,44,243,51.0,pass
29,30,Veena Reddy R,f,16.0,checkers,85,49,40,50,53,64,341,68.0,pass
30,31,Vijay Kumar T.N,f,16.0,cricket,85,61,67,42,61,68,384,77.0,pass
31,12,Keerthi M.N,m,NaN,chess,74,30,37,30,40,45,256,51.0,pass
32,24,Sofiya Khanam,f,17.0,checkers,67,55,66,38,54,46,326,65.0,pass
33,25,Srikanth K.B,f,16.0,volleyball,78,35,0,Ab,49,59,221,44.0,fail
34,26,Sushmitha P,f,16.0,volleyball,77,42,40,43,51,50,303,61.0,pass
35,21,Shanmukha G.S,m,18.0,chess,72,34,37,17,38,23,221,46.0,pass
36,22,Shravani C.N,f,16.0,chess,82,54,52,30,52,57,327,65.0,pass

In [ ]:
df['publishTime']=pd.to_datetime(df['publishTime])

In [30]:
df1['likecount']=pd.to_numeric(df1['likecount'])

KeyError: 'likecount'

In [32]:
#loc and iloc
df1.iloc[1,3]

16.0

In [33]:
df1.iloc[:5]

,Sl,Student,Gender,Age,Hobbies,Kan,Eng,Hin,Math,Sci,S.S.,Total,Perc,Result
0,1,Adhil Pasha,m,17.0,cricket,81,66,77,52,45,59,380,76.0,pass
1,2,Anjali P.S,f,16.0,chess,49,35,25,25,25,33,192,38.0,fail
2,3,Asfiya Z,f,17.0,cricket,60,53,66,47,48,66,340,68.0,pass
3,4,Bharath Kumar M.V,m,NaN,checkers,85,62,68,46,64,78,403,81.0,pass
4,5,Bhargav Reddy Y.S,m,NaN,hockey,90,42,64,40,58,72,366,73.0,pass

In [34]:
df1.iloc[[5]]

,Sl,Student,Gender,Age,Hobbies,Kan,Eng,Hin,Math,Sci,S.S.,Total,Perc,Result
5,6,Bhavani P.V,f,15.0,chess,84,47,57,34,45,53,320,64.0,pass

In [37]:
df1.iloc[4:10]

,Sl,Student,Gender,Age,Hobbies,Kan,Eng,Hin,Math,Sci,S.S.,Total,Perc,Result
4,5,Bhargav Reddy Y.S,m,NaN,hockey,90,42,64,40,58,72,366,73.0,pass
5,6,Bhavani P.V,f,15.0,chess,84,47,57,34,45,53,320,64.0,pass
6,7,Chandra Kanth V.N,m,16.0,chess,77,59,61,38,46,59,340,68.0,pass
7,8,Dharani R.B,f,16.0,checkers,78,56,51,53,52,57,347,69.0,pass
8,9,Divya T.D,f,17.0,checkers,80,51,70,33,54,33,321,64.0,pass
9,10,Janaki G.J,f,NaN,checkers,94,55,64,41,54,48,356,71.0,pass

In [41]:
df1.loc[df1['Student']=='Bhavani P.V']

,Sl,Student,Gender,Age,Hobbies,Kan,Eng,Hin,Math,Sci,S.S.,Total,Perc,Result
5,6,Bhavani P.V,f,15.0,chess,84,47,57,34,45,53,320,64.0,pass

In [45]:
df1.loc[df1['Student']=='Bhavani P.V']

,Sl,Student,Gender,Age,Hobbies,Kan,Eng,Hin,Math,Sci,S.S.,Total,Perc,Result
5,6,Bhavani P.V,f,15.0,chess,84,47,57,34,45,53,320,64.0,pass

In [48]:
df1.columns

Index(['Sl', 'Student', 'Gender ', 'Age', 'Hobbies ', 'Kan', 'Eng', 'Hin',
       'Math', 'Sci', 'S.S.', 'Total', 'Perc', 'Result '],
      dtype='object')

In [46]:
df1.loc[df1['Hobbies ']=='chess']

,Sl,Student,Gender,Age,Hobbies,Kan,Eng,Hin,Math,Sci,S.S.,Total,Perc,Result
1,2,Anjali P.S,f,16.0,chess,49,35,25,25,25,33,192,38.0,fail
5,6,Bhavani P.V,f,15.0,chess,84,47,57,34,45,53,320,64.0,pass
6,7,Chandra Kanth V.N,m,16.0,chess,77,59,61,38,46,59,340,68.0,pass
11,12,Keerthi M.N,m,NaN,chess,74,30,37,30,40,45,256,51.0,pass
12,13,Misbha Sulthana,f,12.0,chess,66,53,73,34,40,41,307,61.0,pass
20,21,Shanmukha G.S,m,18.0,chess,72,34,37,17,38,23,221,46.0,pass
21,22,Shravani C.N,f,16.0,chess,82,54,52,30,52,57,327,65.0,pass
22,23,Sindhu B.C,f,16.0,chess,91,65,78,47,67,73,421,84.0,pass
31,12,Keerthi M.N,m,NaN,chess,74,30,37,30,40,45,256,51.0,pass
35,21,Shanmukha G.S,m,18.0,chess,72,34,37,17,38,23,221,46.0,pass
36,22,Shravani C.N,f,16.0,chess,82,54,52,30,52,57,327,65.0,pass

In [50]:
df1[(df1['Student']=='Bhavani P.V')&(df1['Hobbies ']=='chess')]

,Sl,Student,Gender,Age,Hobbies,Kan,Eng,Hin,Math,Sci,S.S.,Total,Perc,Result
5,6,Bhavani P.V,f,15.0,chess,84,47,57,34,45,53,320,64.0,pass

In [51]:
df1['Total']=min

In [52]:

df1

,Sl,Student,Gender,Age,Hobbies,Kan,Eng,Hin,Math,Sci,S.S.,Total,Perc,Result
0,1,Adhil Pasha,m,17.0,cricket,81,66,77,52,45,59,<built-in function min>,76.0,pass
1,2,Anjali P.S,f,16.0,chess,49,35,25,25,25,33,<built-in function min>,38.0,fail
2,3,Asfiya Z,f,17.0,cricket,60,53,66,47,48,66,<built-in function min>,68.0,pass
3,4,Bharath Kumar M.V,m,NaN,checkers,85,62,68,46,64,78,<built-in function min>,81.0,pass
4,5,Bhargav Reddy Y.S,m,NaN,hockey,90,42,64,40,58,72,<built-in function min>,73.0,pass
5,6,Bhavani P.V,f,15.0,chess,84,47,57,34,45,53,<built-in function min>,64.0,pass
6,7,Chandra Kanth V.N,m,16.0,chess,77,59,61,38,46,59,<built-in function min>,68.0,pass
7,8,Dharani R.B,f,16.0,checkers,78,56,51,53,52,57,<built-in function min>,69.0,pass
8,9,Divya T.D,f,17.0,checkers,80,51,70,33,54,33,<built-in function min>,64.0,pass
9,10,Janaki G.J,f,NaN,checkers,94,55,64,41,54,48,<built-in function min>,71.0,pass
10,11,Ghansi Rani S,f,17.0,checkers,92,62,71,50,52,59,<built-in function min>,77.0,pass
11,12,Keerthi M.N,m,NaN,chess,74,30,37,30,40,45,<built-in function min>,51.0,pass
12,13,Misbha Sulthana,f,12.0,chess,66,53,73,34,40,41,<built-in function min>,61.0,pass
13,14,Mohammed Sulaiman,m,17.0,cricket,72,66,72,41,58,50,<built-in function min>,72.0,pass
14,15,Naresha K.A,m,NaN,cricket,60,38,44,30,46,46,<built-in function min>,53.0,pass
15,16,Neha Khanam,f,15.0,cricket,51,51,56,44,44,40,<built-in function min>,57.0,pass
16,17,Noorain Sadiya,f,16.0,cricket,60,57,72,34,43,54,<built-in function min>,64.0,pass
17,18,Sameer Khan,m,18.0,cricket,92,71,79,53,71,75,<built-in function min>,88.0,pass
18,19,Samreen,m,16.0,cricket,90,53,76,45,50,47,<built-in function min>,72.0,pass
19,20,Sanjay Reddy P.G,m,16.0,cricket,83,44,57,28,43,59,<built-in function min>,63.0,pass
20,21,Shanmukha G.S,m,18.0,chess,72,34,37,17,38,23,<built-in function min>,46.0,pass
21,22,Shravani C.N,f,16.0,chess,82,54,52,30,52,57,<built-in function min>,65.0,pass
22,23,Sindhu B.C,f,16.0,chess,91,65,78,47,67,73,<built-in function min>,84.0,pass
23,24,Sofiya Khanam,f,17.0,checkers,67,55,66,38,54,46,<built-in function min>,65.0,pass
24,25,Srikanth K.B,f,16.0,volleyball,78,35,0,Ab,49,59,<built-in function min>,44.0,fail
25,26,Sushmitha P,f,16.0,volleyball,77,42,40,43,51,50,<built-in function min>,61.0,pass
26,27,Syed Safeer,m,17.0,cricket,82,61,74,42,61,70,<built-in function min>,78.0,pass
27,28,Tanziya Banu A.I,f,16.0,checkers,93,69,79,50,71,76,<built-in function min>,87.6,pass
28,29,Upendra C.V,m,17.0,cricket,70,40,35,18,36,44,<built-in function min>,51.0,pass
29,30,Veena Reddy R,f,16.0,checkers,85,49,40,50,53,64,<built-in function min>,68.0,pass
30,31,Vijay Kumar T.N,f,16.0,cricket,85,61,67,42,61,68,<built-in function min>,77.0,pass
31,12,Keerthi M.N,m,NaN,chess,74,30,37,30,40,45,<built-in function min>,51.0,pass
32,24,Sofiya Khanam,f,17.0,checkers,67,55,66,38,54,46,<built-in function min>,65.0,pass
33,25,Srikanth K.B,f,16.0,volleyball,78,35,0,Ab,49,59,<built-in function min>,44.0,fail
34,26,Sushmitha P,f,16.0,volleyball,77,42,40,43,51,50,<built-in function min>,61.0,pass
35,21,Shanmukha G.S,m,18.0,chess,72,34,37,17,38,23,<built-in function min>,46.0,pass
36,22,Shravani C.N,f,16.0,chess,82,54,52,30,52,57,<built-in function min>,65.0,pass

In [53]:
df1=df1[df1['Student'].str.startswith('B')]
df1

,Sl,Student,Gender,Age,Hobbies,Kan,Eng,Hin,Math,Sci,S.S.,Total,Perc,Result
3,4,Bharath Kumar M.V,m,NaN,checkers,85,62,68,46,64,78,<built-in function min>,81.0,pass
4,5,Bhargav Reddy Y.S,m,NaN,hockey,90,42,64,40,58,72,<built-in function min>,73.0,pass
5,6,Bhavani P.V,f,15.0,chess,84,47,57,34,45,53,<built-in function min>,64.0,pass

In [54]:
df1.dropna(axis=0,how='all')

,Sl,Student,Gender,Age,Hobbies,Kan,Eng,Hin,Math,Sci,S.S.,Total,Perc,Result
3,4,Bharath Kumar M.V,m,NaN,checkers,85,62,68,46,64,78,<built-in function min>,81.0,pass
4,5,Bhargav Reddy Y.S,m,NaN,hockey,90,42,64,40,58,72,<built-in function min>,73.0,pass
5,6,Bhavani P.V,f,15.0,chess,84,47,57,34,45,53,<built-in function min>,64.0,pass

In [55]:
df1.dropna(axis=1,how='any')

,Sl,Student,Gender,Hobbies,Kan,Eng,Hin,Math,Sci,S.S.,Total,Perc,Result
3,4,Bharath Kumar M.V,m,checkers,85,62,68,46,64,78,<built-in function min>,81.0,pass
4,5,Bhargav Reddy Y.S,m,hockey,90,42,64,40,58,72,<built-in function min>,73.0,pass
5,6,Bhavani P.V,f,chess,84,47,57,34,45,53,<built-in function min>,64.0,pass